### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by GilChrist19** [cran4linux/bspm#85]
Getting started with the README, I think [c2d4u](https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+) has been deprecated in favor of [r2u](https://github.com/eddelbuettel/r2u).

I believe this only impacts the [Ubuntu](https://github.com/cran4linux/bspm#ubuntu) portion of the README, where we should update the PPA to the r2u github and link the install procedure from [here](https://github.com/cran4linux/bspm#ubuntu).

**Comment by eddelbuettel** [comment]
@marutter and I are working on the actual Ubuntu README for CRAN but it being summer things get interrupted..

Thanks for the heads-up, though, as c2d4u is indeed currently on hiatus so r2u should be the one pointed at.
