### ISSUE TITLE
bspm.sudo = TRUE does not silence messages as indicated

### ISSUE THREAD

**Issue by cboettig** [cran4linux/bspm#87]
reprex:

Run r2u container _as regular user_  (docker)

```
docker run --rm -ti --user docker rocker/r2u:noble R
```

```r
bspm::disable()
options(bspm.sudo = TRUE)
install.packages("glue")
```

I would have thought `bspm::disable()` alone would be enough to opt out of BSPM.  It does turn BSPM off, but the warning messages persist and tell us again and again go set `options(bspm.sudo = TRUE)`.  Seems like this should be unnecessary if BSPM is 'disabled', but even if we manually set `options(bspm.sudo = TRUE)` as shown above, we still get this very noisy chatter repeatedly:

```
** building package indices
Warning message:
D-Bus service not found!

- If you are in a container environment, please consider adding the
  following to your configuration to silence this warning:

  options(bspm.sudo = TRUE)

- If you are in a desktop/server environment, please remove any 'bspm'
  installation from the user library and force a new system
  installation as follows:

  $ sudo Rscript --vanilla -e 'install.packages("bspm", repos="https://cran.r-project.org")' 
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning message:
D-Bus service not found!

- If you are in a container environment, please consider adding the
  following to your configuration to silence this warning:

  options(bspm.sudo = TRUE)

- If you are in a desktop/server environment, please remove any 'bspm'
  installation from the user library and force a new system
  installation as follows:

  $ sudo Rscript --vanilla -e 'install.packages("bspm", repos="https://cran.r-project.org")' 
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Warning message:
D-Bus service not found!

- If you are in a container environment, please consider adding the
  following to your configuration to silence this warning:

  options(bspm.sudo = TRUE)

- If you are in a desktop/server environment, please remove any 'bspm'
  installation from the user library and force a new system
  installation as follows:

  $ sudo Rscript --vanilla -e 'install.packages("bspm", repos="https://cran.r-project.org")' 
** testing if installed package keeps a record of temporary installation path
* DONE (glue)
```

**Comment by Enchufa2** [comment]
`options(bspm.sudo = TRUE)` does silence the warning _if you set it **before** enabling `bspm`_. In this image, `bspm::enable()` runs in the `Rprofile.site`.

May I ask what are you trying to do here? You are using @eddelbuettel's `r2u`, the image that enables `bspm` by default in the `Rprofile.site` to install binary packages. But at the same time you are running it as a regular user without `sudo`, so you cannot install binary packages. Both things are not compatible.

**Comment by eddelbuettel** [comment]
Howdy @Enchufa2 -- Carl and I discussed over slack. This is essentially 'two-staged': prepare a decent compute environment, relying on r2y ... but then handing it over to users / to deployment where root is not an option.

So we were looking at the best ways to 'have bspm' but to then turn it off.  My hackish recommendation was to `sed` process Rprofile.site so that `bspm` is not awoken in later runs.

**Comment by cboettig** [comment]
Thanks!  apologies I didn't provide more context, I provided the above code only as a minimal illustration of what I viewed to be unexpected behavior of the package, not as an illustration of a realistic use case per se.  I should have provided more context.  

I've worked with @eddelbuettel for over a decade on the Rocker project and how it sets up bspm.  I'm interested in leveraging bspm in a setting that we commonly see in the JupyterHub / 2i2c community and projects like repo2docker or dev-containers, in which there are usually two different settings in which packages may be installed.  In these settings, most packages are installed non-interactively, when a docker image or similar container is built from configurations that are set by a user who may not be expert in linux package installation, but does have root.  BSPM is, in my opinion, the ideal solution here to ensure this maintainer can write recipes that quickly and easily install the desired R packages.  

However, it is very common for these prebuilt containers to then be run in environments such as JupyterHub that do not necessarily grant the end user (or the container) sudo privileges (even if these are granted in the container).    In this situation, it is natural to want to turn `bspm` off for the end user. 


I see your point about the order of operations here in running `bspm::enable()` .  Apologies if that is indeed the intended behavior, but it just felt to me like a bug that `bspm::enable()` has effects that cannot be reversed by running `bspm::disable()`.  Likewise, the error message that suggests we use  `options(bspm.sudo = TRUE)` doesn't mention the fact that this suggestion will not in fact work if `bspm::enable()` has already been called, nor that disable won't resolve it.  Given that presumably a user can never see this error message unless they at some point enabled bspm, they might also be confused like me?  I think ideally we should be able to reverse all the side-effects of bspm::enable() by disabling, but if not, the warning message should probably mention "before you enable bspm()".  

did that make sense?  oh and now I see Dirk has put it more consisely!

**Comment by Enchufa2** [comment]
So you'd like bspm as root, no bspm as user. I suggest moving `bspm::enable()` to `/root/.Rprofile` instead of `/etc/R/Rprofile.site`.

**Comment by Enchufa2** [comment]
About the warning, `bspm::enable()` basically checks that everything is fine and shows this warning if not. The warning was added because a silent non-working installation caused confusion and pain.

Of course, there is no way to disable something that already happened. Moreover, you see more warnings after disabling bspm _for the current session_ because it is enabled site-wide, and therefore every _new_ session will enable bspm (including the new sessions for a staged installation of a package).

The warning is therefore telling you to modify _your configuration_ (i.e. typically the Rprofile where `enable()` was added). It doesn't mention the `.Rprofile` explicitly because, if the user adds this to their home `.Rprofile`, of course it's also pointless, as this will run _after_ the `Rprofile.site`.

Closing here. Please let me know if you need further assistance.

**Comment by eddelbuettel** [comment]
Yes that seems reasonable. I had mentioned to @cboettig that I do just this (root vs user(s)) on one large server, I guess the mindset here was 'initial setup phase' versus later usage phase.
